stages:
- compile
- test
- build
- package

compile:extension:
  stage: compile
  image: node:10
  script:
  - cd extension
  - npm install
  - npm run-script build

test:daemon:
  stage: test
  image: golang:1.11
  script:
  - cd daemon
  - go test -cover -v ./...

test:extension:
  stage: test
  image: node:10
  script:
  - cd extension
  - npm install
  - npm run-script test

build:daemon:linux:
  stage: build
  image: golang:1.11
  script:
  - cd daemon
  - GOOS=linux GOARCH=amd64 go build -v ./...
  artifacts:
    paths:
    - /builds/phil9909/gitlab-local-connector/daemon/gitlab-local-connector

#build:daemon:mac:
#  stage: build
#  image: golang:1.11
#  script:
#  - cd daemon
#  - GOOS=darwin GOARCH=amd64 go build -v ./...
#  artifacts:
#    paths:
#    - /builds/phil9909/gitlab-local-connector/daemon/gitlab-local-connector

build:daemon:windows:
  stage: build
  image: golang:1.11
  script:
  - cd daemon
  - GOOS=windows GOARCH=amd64 go build -v ./...
  artifacts:
    paths:
    - /builds/phil9909/gitlab-local-connector/daemon/gitlab-local-connector.exe

build:extension:
  stage: build
  image: node:10
  script:
  - cd extension
  - 'sed -ri "s=\"version\": \"([^\"]*)=\"version\": \"\\1.$(git log --oneline | wc -l)=" manifest.json' # set the version number from x.x.x to x.x.x.buildnum
  - npm install
  - npm run-script build
  - npm run-script pack
  artifacts:
    paths:
    - extension/extension.zip


package:linux:
  stage: package
  image:
    name: phil9909/fpm
    entrypoint: [""]
  dependencies:
  - build:daemon:linux
  script:
  - cd daemon
  - mkdir bin
  - mv gitlab-local-connector ./bin/git-local-connectord
  - 'VERSION=$(grep -Po "(?<=\"version\": \")[^\"]*" ../extension/package.json).$(git log --oneline | wc -l)'
  - fpm -t deb -n git-local-connector -v $VERSION -a amd64 -p git-local-connector.deb -s dir ./bin=/usr
  artifacts:
    paths:
      - 'daemon/*.deb'

package:windows:
  stage: package
  image:
    name: phil9909/mono-choco-git
    entrypoint: [""]
  dependencies:
  - build:daemon:windows
  script:
  - cd daemon/nuget/git-local-connector
  - mv ../../gitlab-local-connector.exe gitlab-local-connector.exe
  - tar -cf gitlab-local-connector.tar gitlab-local-connector.exe
  - 'VERSION=$(grep -Po "(?<=\"version\": \")[^\"]*" ../../../extension/package.json).$(git log --oneline | wc -l)'
  - sed -i "s/SED_VERSION_HERE/$VERSION/" git-local-connector.nuspec
  - choco pack
  artifacts:
    paths:
      - 'daemon/nuget/git-local-connector/*.nupkg'
