stages:
- compile
- test
- build

before_script:
- cd extension
- npm install

compile:daemon:
  stage: compile
  image: golang:1.11
  script:
  - cd daemon
  - go build -v ./...

compile:extension:
  stage: compile
  image: node:10
  script:
  - cd extension
  - npm run-script build

test:daemon:
  stage: test
  image: golang:1.11
  script:
  - cd daemon
  - go test -cover -v ./...

test:extension:
  stage: test
  image: node:10
  script:
  - npm run-script build